#ifndef _FONTS_H_
#define _FONTS_H_

#include "../graphics/bitmap_font.h"


extern const font_t default_font;

#define WEATHER_CELSIUS                                         1
#define WEATHER_CLOUDY_GUSTS                                    2
#define WEATHER_CLOUDY_WINDY                                    3
#define WEATHER_CLOUDY                                          4
#define WEATHER_CLOUDY_HIGH_DAY                                 5
#define WEATHER_CLOUDY_DAY                                      6
#define WEATHER_HAIL_DAY                                        7
#define WEATHER_HAZE_DAY                                        8
#define WEATHER_LIGHT_WIND_DAY                                  9
#define WEATHER_LIGHTNING_DAY                                   10
#define WEATHER_RAIN_MIX_DAY                                    11
#define WEATHER_RAIN_DAY                                        12
#define WEATHER_SHOWERS_DAY                                     13
#define WEATHER_SLEET_STORM_DAY                                 14
#define WEATHER_SLEET_DAY                                       15
#define WEATHER_SNOW_THUNDERSTORM_DAY                           16
#define WEATHER_SNOW_WIND_DAY                                   17
#define WEATHER_SNOW_DAY                                        18
#define WEATHER_SPRINKLE_DAY                                    19
#define WEATHER_STORM_SHOWERS_DAY                               20
#define WEATHER_SUNNY_OVERCAST_DAY                              21
#define WEATHER_SUNNY_DAY                                       22
#define WEATHER_THUNDERSTORM_DAY                                23
#define WEATHER_WINDY_DAY                                       24
#define WEATHER_SUN_HORIZON_ALT                                 25
#define WEATHER_SUN_HORIZON                                     26
#define WEATHER_MOON_ALT_FIRST_Q                                27
#define WEATHER_MOON_ALT_FULL                                   28
#define WEATHER_MOON_ALT_NEW                                    29
#define WEATHER_MOON_ALT_THIRD_Q                                30
#define WEATHER_MOON_ALT_WARN_CRES_1                            31
#define WEATHER_MOON_ALT_WARN_CRES_2                            32
#define WEATHER_MOON_ALT_WARN_CRES_3                            33
#define WEATHER_MOON_ALT_WARN_CRES_4                            34
#define WEATHER_MOON_ALT_WARN_CRES_5                            35
#define WEATHER_MOON_ALT_WARN_CRES_6                            36
#define WEATHER_MOON_ALT_WARN_GIBB_1                            37
#define WEATHER_MOON_ALT_WARN_GIBB_2                            38
#define WEATHER_MOON_ALT_WARN_GIBB_3                            39
#define WEATHER_MOON_ALT_WARN_GIBB_4                            40
#define WEATHER_MOON_ALT_WARN_GIBB_5                            41
#define WEATHER_MOON_ALT_WARN_GIBB_6                            42
#define WEATHER_MOON_ALT_WAX_CRES_1                             43
#define WEATHER_MOON_ALT_WAX_CRES_2                             44
#define WEATHER_MOON_ALT_WAX_CRES_3                             45
#define WEATHER_MOON_ALT_WAX_CRES_4                             46
#define WEATHER_MOON_ALT_WAX_CRES_5                             47
#define WEATHER_MOON_ALT_WAX_CRES_6                             48
#define WEATHER_MOON_ALT_WAX_GIBB_1                             49
#define WEATHER_MOON_ALT_WAX_GIBB_2                             50
#define WEATHER_MOON_ALT_WAX_GIBB_3                             51
#define WEATHER_MOON_ALT_WAX_GIBB_4                             52
#define WEATHER_MOON_ALT_WAX_GIBB_5                             53
#define WEATHER_MOON_ALT_WAX_GIBB_6                             54
#define WEATHER_MOON_FIRST_Q                                    55
#define WEATHER_MOON_FULL                                       29
#define WEATHER_MOON_NEW                                        56
#define WEATHER_MOON_THIRD_Q                                    57
#define WEATHER_MOON_WARN_CRES_1                                58
#define WEATHER_MOON_WARN_CRES_2                                59
#define WEATHER_MOON_WARN_CRES_3                                60
#define WEATHER_MOON_WARN_CRES_4                                61
#define WEATHER_MOON_WARN_CRES_5                                62
#define WEATHER_MOON_WARN_CRES_6                                63
#define WEATHER_MOON_WARN_GIBB_1                                64
#define WEATHER_MOON_WARN_GIBB_2                                65
#define WEATHER_MOON_WARN_GIBB_3                                66
#define WEATHER_MOON_WARN_GIBB_4                                67
#define WEATHER_MOON_WARN_GIBB_5                                68
#define WEATHER_MOON_WARN_GIBB_6                                69
#define WEATHER_MOON_WAX_CRES_1                                 70
#define WEATHER_MOON_WAX_CRES_2                                 71
#define WEATHER_MOON_WAX_CRES_3                                 72
#define WEATHER_MOON_WAX_CRES_4                                 73
#define WEATHER_MOON_WAX_CRES_5                                 74
#define WEATHER_MOON_WAX_CRES_6                                 75
#define WEATHER_MOON_WAX_GIBB_1                                 76
#define WEATHER_MOON_WAX_GIBB_2                                 77
#define WEATHER_MOON_WAX_GIBB_3                                 78
#define WEATHER_MOON_WAX_GIBB_4                                 79
#define WEATHER_MOON_WAX_GIBB_5                                 80
#define WEATHER_MOON_WAX_GIBB_6                                 81
#define WEATHER_CLOUDY_HIGH_NIGHT_ALT                           82                                
#define WEATHER_CLOUDY_NIGHT_ALT                                83                                
#define WEATHER_HAIL_NIGHT_ALT                                  84
#define WEATHER_LIGHTNING_NIGHT_ALT                             85    
#define WEATHER_PARTLY_CLOUDY_NIGHT_ALT                         86        
#define WEATHER_RAIN_MIX_NIGHT_ALT                              87    
#define WEATHER_RAIN_WIND_NIGHT_ALT                             88    
#define WEATHER_RAIN_NIGHT_ALT                                  89
#define WEATHER_SHOWERS_NIGHT_ALT                               90    
#define WEATHER_SLEET_STORM_NIGHT_ALT                           91        
#define WEATHER_SLEET_NIGHT_ALT                                 92
#define WEATHER_SNOW_THUNDERSTORM_NIGHT_ALT                     93            
#define WEATHER_SNOW_WIND_NIGHT_ALT                             94    
#define WEATHER_SNOW_NIGHT_ALT                                  95
#define WEATHER_SPRINKLE_NIGHT_ALT                              96    
#define WEATHER_STORM_SHOWERS_NIGHT_ALT                         97        
#define WEATHER_THUNDERSTORM_NIGHT_ALT                          98        
#define WEATHER_CLEAR_NIGHT                                     99    
#define WEATHER_CLOUD_GUSTS_NIGHT                               100    
#define WEATHER_CLOUDY_HIGH_NIGHT                               101    
#define WEATHER_CLOUDY_WINDY_NIGHT                              102        
#define WEATHER_CLOUDY_NIGHT                                    103
#define WEATHER_FOG_NIGHT                                       104
#define WEATHER_HAIL_NIGHT                                      105
#define WEATHER_LIGHTNING_NIGHT                                 106
#define WEATHER_PARTLY_CLOUDY_NIGHT                             107
#define WEATHER_RAIN_MIX_NIGHT                                  108
#define WEATHER_RAIN_WIND_NIGHT                                 109
#define WEATHER_RAIN_NIGHT                                      110
#define WEATHER_SHOWERS_NIGHT                                   111
#define WEATHER_SLEET_STORM_NIGHT                               112
#define WEATHER_SLEET_NIGHT                                     113
#define WEATHER_SNOW_THUNDERSTORM_NIGHT                         114
#define WEATHER_SNOW_WIND_NIGHT                                 115
#define WEATHER_SNOW_NIGHT                                      116
#define WEATHER_SPRINKLE_NIGHT                                  117
#define WEATHER_STORM_SHOWERS_NIGHT                             118
#define WEATHER_THUNDERSTORM_NIGHT                              119
#define WEATHER_CLOCK_1                                         120
#define WEATHER_CLOCK_10                                        121
#define WEATHER_CLOCK_11                                        122
#define WEATHER_CLOCK_12                                        123
#define WEATHER_CLOCK_2                                         124
#define WEATHER_CLOCK_3                                         125
#define WEATHER_CLOCK_4                                         126
#define WEATHER_CLOCK_5                                         127
#define WEATHER_CLOCK_6                                         128
#define WEATHER_CLOCK_7                                         129
#define WEATHER_CLOCK_8                                         130
#define WEATHER_CLOCK_9                                         131
#define WEATHER_BEAUFORT_0                                      132
#define WEATHER_BEAUFORT_1                                      133
#define WEATHER_BEAUFORT_2                                      134
#define WEATHER_BEAUFORT_3                                      135
#define WEATHER_BEAUFORT_4                                      136
#define WEATHER_BEAUFORT_5                                      137
#define WEATHER_BEAUFORT_6                                      138
#define WEATHER_BEAUFORT_7                                      139
#define WEATHER_BEAUFORT_8                                      140
#define WEATHER_BEAUFORT_9                                      141
#define WEATHER_BEAUFORT_10                                     142
#define WEATHER_BEAUFORT_11                                     143
#define WEATHER_BEAUFORT_12                                     144
#define WEATHER_SUN_RISE                                        145
#define WEATHER_SUN_SET                                         146
#define WEATHER_THERMOMETER                                     147

extern const font_t weather_font;


#endif /* _FONTS_H_ */